function rebuild_all_features(numWorkers)
%REBUILD_ALL_FEATURES Reconstruct both subjects' feature MAT files.

if nargin < 1 || isempty(numWorkers)
    numWorkers = 0;
end

repositoryDir = fileparts(mfilename('fullpath'));
abDir = fullfile(repositoryDir, 'respFocusSaccAb');
raDir = fullfile(repositoryDir, 'respFocusSaccRa');
addpath(abDir, '-end');

fprintf('Rebuilding Monkey Ab features...\n');
abOutput = fullfile(abDir, ...
    'respFeaturesAb.mat');
extractRespFeaturesFromPublicationData( ...
    'InputDir', fullfile(abDir, 'publication_data'), ...
    'OutputFile', abOutput, ...
    'Subject', 'Ab', ...
    'OutputVariable', 'respFeaturesAb', ...
    'NumWorkers', numWorkers);

fprintf('Rebuilding Monkey Ra features...\n');
raOutput = fullfile(raDir, ...
    'respFeaturesRa.mat');
extractRespFeaturesFromPublicationData( ...
    'InputDir', fullfile(raDir, 'publication_data'), ...
    'OutputFile', raOutput, ...
    'Subject', 'Ra', ...
    'OutputVariable', 'respFeaturesRa', ...
    'NumWorkers', numWorkers);

fprintf('Both subject feature files were rebuilt successfully.\n');
end
