function rebuild_all_features(numWorkers)
%REBUILD_ALL_FEATURES Reconstruct both subjects' feature MAT files.

if nargin < 1 || isempty(numWorkers)
    numWorkers = 0;
end

repositoryDir = fileparts(mfilename('fullpath'));
abooDir = fullfile(repositoryDir, 'respFocusSaccAboo');
rafDir = fullfile(repositoryDir, 'respFocusSaccRaf');
addpath(abooDir, '-end');

fprintf('Rebuilding Monkey Aboo features...\n');
abooOutput = fullfile(abooDir, ...
    'respFeatAbooV1V4Array_fromPublicationData.mat');
respFeatAbooV1V4Array = extractRespFeaturesFromPublicationData( ...
    'InputDir', fullfile(abooDir, 'publication_data'), ...
    'OutputFile', abooOutput, ...
    'Subject', 'Aboo', ...
    'OutputVariable', 'respFeatAbooV1V4Array', ...
    'NumWorkers', numWorkers);
save(fullfile(abooDir, 'respFeatAbooV1V4Array.mat'), ...
    'respFeatAbooV1V4Array', '-v7.3');

fprintf('Rebuilding Monkey Raf features...\n');
rafOutput = fullfile(rafDir, ...
    'respFeatRafV1V4Array_fromPublicationData.mat');
respFeatRafV1V4Array = extractRespFeaturesFromPublicationData( ...
    'InputDir', fullfile(rafDir, 'publication_data'), ...
    'OutputFile', rafOutput, ...
    'Subject', 'Raf', ...
    'OutputVariable', 'respFeatRafV1V4Array', ...
    'NumWorkers', numWorkers);
save(fullfile(rafDir, 'respFeatRafV1V4Array.mat'), ...
    'respFeatRafV1V4Array', '-v7.3');

% The combined Monkey RA/AB Figure 3 script in the Raf folder expects the
% Aboo feature MAT beside it.
save(fullfile(rafDir, 'respFeatAbooV1V4Array.mat'), ...
    'respFeatAbooV1V4Array', '-v7.3');

fprintf('Both subject feature files were rebuilt successfully.\n');
end
