function rebuild_all_features(numWorkers)
%REBUILD_ALL_FEATURES Reconstruct both subjects' feature MAT files.

if nargin < 1 || isempty(numWorkers)
    numWorkers = 0;
end

repositoryDir = fileparts(mfilename('fullpath'));
abooDir = fullfile(repositoryDir, 'respFocusSaccAboo');
rafDir = fullfile(repositoryDir, 'respFocusSaccRaf');
addpath(abooDir, '-end');

fprintf('Rebuilding Monkey Aboo features...\n');
abooOutput = fullfile(abooDir, ...
    'respFeaturesAboo.mat');
extractRespFeaturesFromPublicationData( ...
    'InputDir', fullfile(abooDir, 'publication_data'), ...
    'OutputFile', abooOutput, ...
    'Subject', 'Aboo', ...
    'OutputVariable', 'respFeaturesAboo', ...
    'NumWorkers', numWorkers);

fprintf('Rebuilding Monkey Raf features...\n');
rafOutput = fullfile(rafDir, ...
    'respFeaturesRaf.mat');
extractRespFeaturesFromPublicationData( ...
    'InputDir', fullfile(rafDir, 'publication_data'), ...
    'OutputFile', rafOutput, ...
    'Subject', 'Raf', ...
    'OutputVariable', 'respFeaturesRaf', ...
    'NumWorkers', numWorkers);

fprintf('Both subject feature files were rebuilt successfully.\n');
end
