function [abReport, raReport] = validate_all_data()
%VALIDATE_ALL_DATA Validate all public session and derived feature MAT files.

repositoryDir = fileparts(mfilename('fullpath'));
abDir = fullfile(repositoryDir, 'respFocusSaccAb');
raDir = fullfile(repositoryDir, 'respFocusSaccRa');
addpath(abDir, '-end');

abReport = validateRespPublicationData( ...
    'InputDir', fullfile(abDir, 'publication_data'), ...
    'FeatureFile', fullfile(abDir, ...
        'respFeaturesAb.mat'), ...
    'Subject', 'Ab', ...
    'FeatureVariable', 'respFeaturesAb', ...
    'ExpectedSessionCount', 47);

raReport = validateRespPublicationData( ...
    'InputDir', fullfile(raDir, 'publication_data'), ...
    'FeatureFile', fullfile(raDir, ...
        'respFeaturesRa.mat'), ...
    'Subject', 'Ra', ...
    'FeatureVariable', 'respFeaturesRa', ...
    'ExpectedSessionCount', 41);

fprintf('All 88 publication session files passed validation.\n');
end
