function [abooReport, rafReport] = validate_all_data()
%VALIDATE_ALL_DATA Validate all public session and derived feature MAT files.

repositoryDir = fileparts(mfilename('fullpath'));
abooDir = fullfile(repositoryDir, 'respFocusSaccAboo');
rafDir = fullfile(repositoryDir, 'respFocusSaccRaf');
addpath(abooDir, '-end');

abooReport = validateRespPublicationData( ...
    'InputDir', fullfile(abooDir, 'publication_data'), ...
    'FeatureFile', fullfile(abooDir, ...
        'respFeaturesAboo.mat'), ...
    'Subject', 'Aboo', ...
    'FeatureVariable', 'respFeaturesAboo', ...
    'ExpectedSessionCount', 47);

rafReport = validateRespPublicationData( ...
    'InputDir', fullfile(rafDir, 'publication_data'), ...
    'FeatureFile', fullfile(rafDir, ...
        'respFeaturesRaf.mat'), ...
    'Subject', 'Raf', ...
    'FeatureVariable', 'respFeaturesRaf', ...
    'ExpectedSessionCount', 41);

fprintf('All 88 publication session files passed validation.\n');
end
